#!/usr/bin/env sh

set +x

VIDEO_OUT=program
HLS_TIME=4
FPS=50
GOP_SIZE=100
PRESET_P=veryfast

cd stream

# HLS
ffmpeg -i $VIDEO_IN -y \
    -c:v copy -c:a libfdk_aac \
    -b:v 5000k -b:a 192k \
    -f hls -hls_time $HLS_TIME \
    -hls_flags independent_segments \
    -hls_playlist_type event \
    -hls_segment_type fmp4 \
    -master_pl_publish_rate 10 \
    -strftime_mkdir 1 \
    -master_pl_name $VIDEO_OUT.m3u8 \
    -hls_segment_filename hls_%v/s%06d.m4s \
    program_%v.m3u8
